# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

WORKDIR /app

# Install dependencies
COPY pyproject.toml uv.lock .
RUN pip install --no-cache-dir .

# Copy source
COPY . .

# Use unbuffered stdout/stderr
ENV PYTHONUNBUFFERED=1

# Default command to run the MCP server over stdio
CMD ["python", "-u", "weather.py"]
